object Testing {
    const val JUNIT4 = "junit:junit:${Versions.JUNIT4}"
    const val JUNIT4_TEST = "androidx.test.ext:junit-ktx:${Versions.JUNIT4_TEST}"
    const val TRUTH = "androidx.test.ext:truth:${Versions.TRUTH}"
    const val TRUTH_CORE = "androidx.test:core:${Versions.TRUTH_CORE}"
    const val TRUTH_EXT = "androidx.test.ext:truth:${Versions.TRUTH_EXT}"
    const val RUNNER = "androidx.test:runner:${Versions.RUNNER}"
    const val ROBOLECTRIC = "org.robolectric:robolectric:${Versions.ROBOLECTRIC}"
    const val RUNNER_ANDROID = "androidx.test:runner:${Versions.RUNNER_ANDROID}"
    const val ANDROID_JUNIT = "androidx.test.ext:junit:${Versions.ANDROID_JUNIT}"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core:${Versions.ESPRESSO_CORE}"
    const val ESPRESSO_CONTRIB = "androidx.test.espresso:espresso-contrib:${Versions.ESPRESSO_CONTRIB}"
    const val HAMCREST = "org.hamcrest:hamcrest:${Versions.HAMCREST}"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.COROUTINE}"
    const val HILT_TEST = "com.google.dagger:hilt-android-testing:${Versions.HILT_TEST}"
    const val HILT_TEST_COMPILER = "com.google.dagger:hilt-android-compiler:${Versions.HILT_COMPILER}"
}
